"""Added Relationships

Revision ID: 59dbb6bb06c0
Revises: 798cd5f423f0
Create Date: 2026-06-07 15:56:20.112727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59dbb6bb06c0'
down_revision: Union[str, Sequence[str], None] = '798cd5f423f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('daily_repeats', sa.Column('last_occurrence', sa.DateTime(), nullable=True))
    op.add_column('monthly_repeats', sa.Column('last_occurrence', sa.DateTime(), nullable=True))
    op.add_column('weekly_repeats', sa.Column('last_occurrence', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_repeats', 'last_occurrence')
    op.drop_column('monthly_repeats', 'last_occurrence')
    op.drop_column('daily_repeats', 'last_occurrence')
    op.drop_table('backlog')
    # ### end Alembic commands ###
